config/routes.rb
LogoBlog::Application.routes.draw do

  root :to => "posts#index"

  match 'contact',  :to => 'pages#contact'
  match 'signup',   :to => 'users#new'
  match 'signin',   :to => 'sessions#new'
  match 'signout',   :to => 'sessions#destroy', :via => :delete

  resources :sessions, :only => [:new, :create, :destroy]

  resources :users

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :header, :content, :user_id
  
  belongs_to :user
  has_many :responses

end

app/models/response.rb
class Response < ActiveRecord::Base
  attr_accessible :content, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  has_many :posts, :dependent => :destroy

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates_presence_of :name, :password, :password_confirmation
  validates_confirmation_of :password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => true, :uniqueness => true, :format => { :with => VALID_EMAIL_REGEX }


  def to_s
    name
  end

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  def index
  end


  def contact
    render "pages/contact"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
  end

  def create
    user = User.find_by_email params[:session][:email].downcase
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_path, :notice => "Login Successful"
    else
      flash.now[:alert] = "Incorrect"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path, :notice => "You have been signed out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to root_path, notice: 'Welcome, Stranger' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.haml
- if signed_in?
  .left
    = link_to "Home", root_path, :class => "button"
    = link_to "Benutzer", users_path, :class => "button"
    = link_to "Posts", posts_path, :class => "button"
    = link_to "Kontakt", contact_path, :class => "button"
  .right
    = link_to current_user.email, current_user, :class => "button"
    = link_to "Log out", signout_path, :method => :delete, :class => "button"
- else
  .right
    = link_to "Log in", signin_path, :class => "button"
    = link_to "Create account", new_user_path, :class => "button"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title LogoBlog
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tag

  %body
    #container
      #notice
        - flash.each do |key, value|
          %div{:class => "alert alert-#{key}"}
            = value
      #header
        //#logo
        //  = link_to image_tag("logo.jpg"), root_path
        %h1= "LogoBlog"
      #container_navi
        = render 'layouts/navigation'
      #container_content
        = yield
      #padding
      
      .debug{:style => "margin-top: 100px"}
        - if Rails.env.development?# || Rails.env.production?
          = debug(params) 
          %div
            = request.user_agent

app/views/pages/contact.html.haml
#contact_address
  %h3
    = "Venus von Hinten"
  %h4
    = "mir-verliere-im-schutte-strasse 12"
  %h4
    = "3015 Buempliz"

app/views/pages/index.html.haml
%h3
  = "Buempliz Frontal mir mache euch kaputt!! lg jobi"

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved"
      %ul
        = @post.errors.full_messages.each do |msg|
          = msg
  .field
    = f.input :header
    = f.input :content, :as => :text
    = f.association :user, :as => :hidden, :input_html => {:value => current_user.id}
  .actions
    = f.submit

app/views/posts/_post_box.html.haml
.post
  %fieldset
    %h3
      = link_to post.header, post
    = post.content
    
    .responses
      - post.responses.first(3).each do |response|
        .response
        = render "response", :response => response

    - if signed_in? && (post.user == current_user)
      .actions
        = link_to 'Show', post
        = link_to 'Edit', edit_post_path(post)
        = link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

app/views/posts/_response.html.haml
= response

app/views/posts/edit.html.haml
%h1
  = "Editing post"

= render 'form'

= link_to 'Show', @post
= link_to 'Back', posts_path

app/views/posts/index.html.haml
#sorting.inline
  = link_to "newest", "#", :class => "button"
  = link_to "most interesting", "#", :class => "button"
  = link_to "other category", "#", :class => "button"
- if signed_in?
  #action_box.inline
    = link_to 'New Post', new_post_path
- @posts.each do |post|
  = render "post_box", :post => post

app/views/posts/new.html.haml
%h1
  = "New post"

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>

<p>
  <b>User:</b>
  <%= @post.user_id %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.haml
%p
  %b= "Content:"
  = @post.content
%p
  %b= "User:"
  = @post.user

= link_to 'Edit', edit_post_path(@post)
= link_to 'Back', posts_path

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved"
      - @user.errors.full_messages.each do |msg|
        = msg
  .field
    = f.input :name
  .field 
    = f.input :email
  .field
    = f.input :password
  .field 
    = f.input :password_confirmation
  .actions
    = f.submit "Save"

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/edit.html.haml
%h1= "Edit User"

= simple_form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved"
      - @user.errors.full_messages.each do |msg|
        = msg
  .field
    = f.input :name
  .field 
    = f.input :email
  .field
    = f.input :password
  .actions
    = f.submit "Save"

= link_to 'Show', @user
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1
  = "Listing users"

%table
  %tr
    %th= "Name"
    %th="Email"
    %th
    %th
    %th
  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1
  = "New User"

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p
  %b= "Name:"
  = @user.name
%p
  %b= "Email:"
  = @user.email

= link_to 'Edit', edit_user_path(@user)
= link_to 'Back', users_path